#!/bin/sh
[% c("var/set_default_env") -%]
# reset HOME which was changed by var/set_default_env, for gpg
[% IF ENV.HOME %]export HOME="[% ENV.HOME %]"[% END %]
destdir="[% dest_dir _ '/' _ c("var/publish_dir") %]"
mkdir -p "$destdir"
[% IF c("var/tor-windows-i686") -%]
  cp [% c('input_files_by_name/windows-i686') %]/tor.zip "$destdir"/tor-windows-i686.zip 
  cp [% c('input_files_by_name/windows-expert-bundle') %]/tor-*.zip $destdir
  cp [% c('input_files_by_name/windows-i686') %]/data.zip $destdir
[% END -%]
[% IF c("var/tor-windows-x86_64") -%]
  cp [% c('input_files_by_name/windows-x86_64') %]/tor.zip "$destdir"/tor-windows-x86_64.zip 
  cp [% c('input_files_by_name/windows64-expert-bundle') %]/tor-*.zip $destdir
  cp [% c('input_files_by_name/windows-x86_64') %]/data.zip $destdir
[% END -%]
[% IF c("var/tor-osx-x86_64") -%]
  cp [% c('input_files_by_name/osx-x86_64') %]/tor.zip "$destdir"/tor-osx-x86_64.zip 
  cp [% c('input_files_by_name/osx-x86_64') %]/data.zip $destdir
[% END -%]
[% IF c("var/tor-linux-i686") -%]
  cp [% c('input_files_by_name/linux-i686') %]/tor.zip "$destdir"/tor-linux-i686.zip 
  cp [% c('input_files_by_name/linux-i686') %]/data.zip $destdir
[% END -%]
[% IF c("var/tor-linux-x86_64") -%]
  cp [% c('input_files_by_name/linux-x86_64') %]/tor.zip "$destdir"/tor-linux-x86_64.zip
  cp [% c('input_files_by_name/linux-x86_64') %]/data.zip $destdir
[% END -%]
